export const ADD_PAUSE_TIME = 'ADD_PAUSE_TIME';
export const CLOCK_IN = 'CLOCK_IN';
export const CLOCK_OUT = 'CLOCK_OUT';
export const CONFIGURATION_CHANGE_WORKING_HOURS = 'CONFIGURATION_CHANGE_WORKING_HOURS';