export const ADD_CLOCK_TIME = 'ADD_CLOCK_TIME';
export const ADD_PAUSE_TIME = 'ADD_PAUSE_TIME';
export const CHANGE_CLOCK_TIME = 'CHANGE_CLOCK_TIME';
export const CLOCK_IN = 'CLOCK_IN';
export const CLOCK_OUT = 'CLOCK_OUT';
export const REMOVE_CLOCK_TIME = 'REMOVE_CLOCK_TIME';
export const CONFIGURATION_CHANGE_WORKING_HOURS = 'CONFIGURATION_CHANGE_WORKING_HOURS';